apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kafka
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer:1.0
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: kafka
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
