apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaled
  namespace: kafka
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: 10.101.19.121:9092
        consumerGroup: kafka
        topic: test-topic
        lagThreshold: "1"
        desiredReplicas: "1"
        offsetResetPolicy: latest
