apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: kafka
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer:1.0
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: kafka
spec:
  selector:
    app: producer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 32321
